AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  AllowedMethods: ["describe", "context", "shared_examples"]

Metrics/MethodLength:
  Max: 15

Naming/PredicateMethod:
  Enabled: false

Style/KeywordArgumentsMerging:
  Enabled: false

Style/RedundantCurrentDirectoryInPath:
  Enabled: false

Gemspec/AddRuntimeDependency:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
