name: CI

on:
  push:

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 3.4
          - 4.0

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Rubocop
      run: bundle exec rubocop
    - name: Rspec
      run: bundle exec rspec --tag ~browser

  browser-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 4.0
        bundler-cache: true
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      id: setup-chrome
    - name: Browser specs (Cuprite)
      run: bundle exec rspec --tag browser
      env:
        CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
